version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - make build
      - aws cloudformation package --template-file apps/pool-manager/stacks/sandbox-administrator-account/pool-manager.yml --s3-bucket $ARTIFACTS_BUCKET --s3-prefix artifacts/aws-sandbox-accounts/apps/pool-manager --output-template-file apps/pool-manager/stacks/sandbox-administrator-account/pool-manager.yml
artifacts:
  files: "**/*"
