version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 22
  build:
    commands:
      # install poetry
      - dnf install -y python3-pip
      - python3 -m pip install --user pipx
      - export PATH=$PATH:/root/.local/bin
      - pipx install poetry==2.1.4
      # db-client
      - cd apps/db-client
      - make test
      - make package
      - aws cloudformation package --template-file stacks/sandbox-administrator-account/db-client.yml --s3-bucket $ARTIFACTS_BUCKET --s3-prefix artifacts/aws-sandbox-accounts/apps/db-client --output-template-file stacks/sandbox-administrator-account/db-client.yml
      - cd ../..
      # auth-client
      - cd apps/auth-client
      - make test
      - make package
      - aws cloudformation package --template-file stacks/sandbox-administrator-account/auth-client.yml --s3-bucket $ARTIFACTS_BUCKET --s3-prefix artifacts/aws-sandbox-accounts/apps/auth-client --output-template-file stacks/sandbox-administrator-account/auth-client.yml
      - cd ../..
      # interface
      - cd apps/interface
      - npm ci
      - npm run build
artifacts:
  files: "**/*"
