version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      # install poetry
      - curl -sSL https://install.python-poetry.org | POETRY_HOME=${HOME}/.poetry python3 -
      # account-manager-db-client
      - cd apps/account-manager-db-client
      # - aws cloudformation package --template-file apps/account-manager-db-client/stacks/sandbox-administrator-account/account-manager-db-client.yml --s3-bucket $ARTIFACTS_BUCKET --s3-prefix artifacts/aws-sandbox-accounts/apps/account-manager-db-client --output-template-file apps/account-manager-db-client/stacks/sandbox-administrator-account/account-manager-db-client.yml
artifacts:
  files: "**/*"
