Transform: AWS::Serverless-2016-10-31
Description: Infrastructure for aws-sandbox-accounts account-manager-db-client
Parameters:
  Environment:
    Description: The infrastructure environment
    Type: String
    AllowedValues:
      - test
      - live
Resources:
  FunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: !Sub "${Environment}-aws-sandbox-accounts-account-manager-db-client"
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: account_manager_db_client.main.handler
      Runtime: python3.12
      CodeUri: ../../build
      Role: !GetAtt FunctionExecutionRole.Arn
      FunctionName: !Sub "${Environment}-aws-sandbox-accounts-account-manager-db-client"
      MemorySize: 256
      Timeout: 120
      Tracing: Active
  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: Errors
      Namespace: AWS/Lambda
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching
      Statistic: Sum
      Threshold: 0
      ActionsEnabled: true
      AlarmActions:
        - !ImportValue notification-topic-arn
      Dimensions:
        - Name: FunctionName
          Value: !Ref Function
