Transform: AWS::Serverless-2016-10-31
Description: Infrastructure for aws-sandbox-accounts account-manager
Parameters:
  Environment:
    Description: The infrastructure environment
    Type: String
    AllowedValues:
      - test
      - live
Resources:
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: state-machine-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:query
                  Resource:
                    - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Environment}-aws-sandbox-accounts-account-pool/index/status"
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${Environment}-aws-sandbox-accounts-account-manager"
      RoleArn: !GetAtt StateMachineRole.Arn
      Definition:
        StartAt: FetchAccounts
        States:
          FetchAccounts:
            Type: Task
            Resource: arn:aws:states:::aws-sdk:dynamodb:query
            End: true
            Parameters:
              TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
              IndexName: status
              KeyConditionExpression: "#pk = :pk AND #sk = :st"
              ExpressionAttributeNames:
                "#pk": pk
                "#sk": status
              ExpressionAttributeValues:
                :pk:
                  S: account
                :st:
                  S: initial
            OutputPath: $.Items
