Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: Infrastructure for aws-sandbox-accounts account-manager
Parameters:
  Environment:
    Description: The infrastructure environment
    Type: String
    AllowedValues:
      - test
      - live
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !ImportValue ci-infrastructure-codebuild-base-iam-policy
      RoleName: !Sub "${Environment}-aws-sandbox-accounts-aws-nuke"
  CodeBuildProjectLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "${Environment}-aws-sandbox-accounts-aws-nuke"
      RetentionInDays: 30
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      TimeoutInMinutes: 10
      Description: runs aws-nuke against sandbox accounts
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Name: !Sub "${Environment}-aws-sandbox-accounts-aws-nuke"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref CodeBuildProjectLogGroup
          Status: ENABLED
      Source:
        Type: GITHUB
        Location: https://github.com/AlexChesters/aws-sandbox-accounts.git
        BuildSpec: apps/account-manager/buildspec.yml
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: state-machine-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:query
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                  Resource:
                    - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Environment}-aws-sandbox-accounts-account-pool"
                - Effect: Allow
                  Action:
                    - codebuild:StartBuild
                    - codebuild:StopBuild
                    - codebuild:BatchGetBuilds
                  Resource:
                    - !GetAtt CodeBuildProject.Arn
                - Effect: Allow
                  Action:
                  - events:PutTargets
                  - events:PutRule
                  - events:DescribeRule
                  Resource:
                  - !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventForCodeBuildStartBuildRule"
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${Environment}-aws-sandbox-accounts-account-manager"
      RoleArn: !GetAtt StateMachineRole.Arn
      # Use DefinitionString rather than Definition so that we can use null values
      DefinitionString:
        Fn::ToJsonString:
          # TODO: need to handle removing the account ID from states that no longer apply
          # e.g. if account has been cleaned and is set to "ready", need to remove it from "account_status#leased"
          StartAt: MarkAccountAsInitial
          States:
            # TEMP - force one account to always be in the initial state for testing purposes
            MarkAccountAsInitial:
              Type: Task
              Resource: arn:aws:states:::aws-sdk:dynamodb:transactWriteItems
              Next: FetchAccounts
              Parameters:
                TransactItems:
                  - Put:
                      TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
                      Item:
                        pk:
                          S: account_id#905418121097
                        data:
                          S: initial
                  - Update:
                      TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
                      Key:
                        pk:
                          S: account_status#all
                      UpdateExpression: "SET #data = list_append(#data, :values)"
                      ExpressionAttributeNames:
                        "#data": data
                      ExpressionAttributeValues:
                        ":values":
                          L:
                            - S: "905418121097"
                  - Update:
                      TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
                      Key:
                        pk:
                          S: account_status#initial
                      UpdateExpression: "SET #data = list_append(#data, :values)"
                      ExpressionAttributeNames:
                        "#data": "data"
                      ExpressionAttributeValues:
                        ":values":
                          L:
                            - S: "905418121097"
            FetchAccounts:
              Type: Task
              Resource: arn:aws:states:::aws-sdk:dynamodb:query
              Next: ProcessAccounts
              Parameters:
                TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
                KeyConditionExpression: "#pk = :pk"
                ExpressionAttributeNames:
                  "#pk": pk
                ExpressionAttributeValues:
                  :pk:
                    S: account_status#initial
              OutputPath: $.Items
            ProcessAccounts:
              Type: Map
              End: true
              ItemSelector:
                account_id.$: $$.Map.Item.Value.sk.S
              ItemProcessor:
                ProcessorConfig:
                  Mode: INLINE
                StartAt: AWSNuke
                States:
                  AWSNuke:
                    Type: Task
                    Resource: arn:aws:states:::codebuild:startBuild.sync
                    TimeoutSeconds: 900
                    Next: MarkAccountAsAvailable
                    ResultPath: null
                    Parameters:
                      ProjectName: !Ref CodeBuildProject
                      EnvironmentVariablesOverride:
                        - Type: PLAINTEXT
                          Name: ACCOUNT_ID
                          Value.$: $.account_id
                    Catch:
                      - ErrorEquals:
                          - States.ALL
                        Next: MarkAccountAsFailed
                        ResultPath: null
                  MarkAccountAsFailed:
                    Type: Task
                    Resource: arn:aws:states:::aws-sdk:dynamodb:transactWriteItems
                    End: true
                    Parameters:
                      TransactItems:
                        - Update:
                            TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
                            Key:
                              pk:
                                S: account_status#failed
                            UpdateExpression: "SET #data = list_append(#data, :values)"
                            ExpressionAttributeNames:
                              "#data": data
                            ExpressionAttributeValues:
                              ":values":
                                L:
                                  - S.$: $.account_id
                        - Update:
                            TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
                            Key:
                              pk:
                                S.$: States.Format("account_id#{}", $.account_id)
                            UpdateExpression: "SET #data = failed"
                            ExpressionAttributeNames:
                              "#data": data
                  MarkAccountAsAvailable:
                    Type: Task
                    Resource: arn:aws:states:::aws-sdk:dynamodb:transactWriteItems
                    End: true
                    Parameters:
                      TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
                      TransactItems:
                        - Update:
                            TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
                            Key:
                              pk:
                                S: account_status#available
                            UpdateExpression: "SET #data = list_append(#data, :values)"
                            ExpressionAttributeNames:
                              "#data": data
                            ExpressionAttributeValues:
                              ":values":
                                L:
                                  - S.$: $.account_id
                        - Update:
                            TableName: !Sub "${Environment}-aws-sandbox-accounts-account-pool"
                            Key:
                              pk:
                                S.$: States.Format("account_id#{}", $.account_id)
                            UpdateExpression: "SET #data = available"
                            ExpressionAttributeNames:
                              "#data": data
