Transform: AWS::Serverless-2016-10-31
Description: Infrastructure for aws-sandbox-accounts interface
Parameters:
  Environment:
    Description: The infrastructure environment
    Type: String
    AllowedValues:
      - test
      - live
Conditions:
  IsTest: !Equals [!Ref Environment, test]
Mappings:
  EnvMap:
    test:
      DomainName: test.sandbox.alexchesters.com
    live:
      DomainName: sandbox.alexchesters.com
Resources:
  Client:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - !Sub
          - "https://${Domain}/auth/_callback"
          - Domain: !FindInMap [EnvMap, !Ref Environment, DomainName]
        - !If
          - IsTest
          - http://localhost:5173/auth/callback
          - !Ref AWS::NoValue
      ClientName: !Sub "${Environment}-aws-sandbox-interface-client"
      GenerateSecret: false
      LogoutURLs:
        - !Sub
          - "https://${Domain}/auth/logout"
          - Domain: !FindInMap [EnvMap, !Ref Environment, DomainName]
        - !If
          - IsTest
          - http://localhost:5173/auth/logout
          - !Ref AWS::NoValue
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId:
        Fn::ImportValue: !Sub "${Environment}-cognito-user-pool-user-pool-id"
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
