Transform:
  - AWS::LanguageExtensions
Description: pipeline to build aws-sandbox-accounts lambda-build-image
Parameters:
  Branch:
    Type: String
    Default: main
    Description: The branch to build from
Resources:
  BuildImageRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-build-image
      LifecyclePolicy:
        LifecyclePolicyText:
          Fn::ToJsonString:
            rules:
              - rulePriority: 1
                description: Only keep 5 images
                selection:
                  tagStatus: any
                  countType: imageCountMoreThan
                  countNumber: 5
                action:
                  type: expire
  BuildImageCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !ImportValue ci-infrastructure-codebuild-base-iam-policy
      Policies:
          - PolicyName: ecr-policy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - ecr:GetAuthorizationToken
                  Resource:
                    - "*"
                - Effect: Allow
                  Action:
                    - ecr:BatchCheckLayerAvailability
                    - ecr:GetDownloadUrlForLayer
                    - ecr:BatchGetImage
                    - ecr:PutImage
                    - ecr:InitiateLayerUpload
                    - ecr:UploadLayerPart
                    - ecr:CompleteLayerUpload
                  Resource:
                    - !GetAtt BuildImageRepository.Arn
  BuildImageCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !ImportValue ci-infrastructure-artifacts-bucket-name
        Path: /artifacts/aws-sandbox-accounts/build-image
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      Description: Builds aws-sandbox-accounts build image
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        PrivilegedMode: true
        Type: ARM_CONTAINER
      Name: aws-sandbox-accounts-lambda-build-image
      ServiceRole: !GetAtt BuildImageCodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: ci/lambda-build-image/buildspec.yml
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !ImportValue ci-infrastructure-artifacts-bucket-name
      Name: aws-sandbox-accounts-lambda-build-image
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue ci-infrastructure-codepipeline-base-execution-iam-role
      PipelineType: V2
      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            SourceActionName: Clone-From-GitHub
            Push:
              - Branches:
                  Includes:
                    - !Ref Branch
                FilePaths:
                  Includes:
                    - ci/lambda-build-image/**
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Clone-From-GitHub
              Namespace: SourceVariables
              Configuration:
                ConnectionArn: !ImportValue ci-infrastructure-github-codestar-connection
                FullRepositoryId: AlexChesters/aws-sandbox-accounts
                BranchName: !Ref Branch
                OutputArtifactFormat: CODE_ZIP
        - Name: Build-Image
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Build-Lambda-Build-Image
              Configuration:
                ProjectName: !Ref BuildImageCodeBuildProject
