Transform:
  - AWS::LanguageExtensions
Description: pipeline to deploy aws-sandbox-accounts
Parameters:
  Branch:
    Type: String
    Default: main
    Description: The branch to build from
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !ImportValue ci-infrastructure-codebuild-base-iam-policy
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !ImportValue ci-infrastructure-artifacts-bucket-name
        Path: /artifacts/aws-sandbox-accounts/apps/build
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      Description: Builds aws-sandbox-accounts
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-aarch64-standard:3.0
        Type: ARM_CONTAINER
        EnvironmentVariables:
          - Value: !ImportValue ci-infrastructure-artifacts-bucket-name
            Name: ARTIFACTS_BUCKET
            Type: PLAINTEXT
      Name: aws-sandbox-accounts-apps
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.build.yml
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStores:
        - Region: eu-west-1
          ArtifactStore:
            Type: S3
            Location: atc-ci-artifacts-654654632738-eu-west-1
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: atc-ci-artifacts-654654632738-us-east-1
      Name: aws-sandbox-accounts-apps
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue ci-infrastructure-codepipeline-base-execution-iam-role
      PipelineType: V2
      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            SourceActionName: Clone-From-GitHub
            Push:
              - Branches:
                  Includes:
                    - !Ref Branch
                FilePaths:
                  Includes:
                    - apps/auth-client/**
                    - apps/db-client/**
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Clone-From-GitHub
              Namespace: SourceVariables
              Configuration:
                ConnectionArn: !ImportValue ci-infrastructure-github-codestar-connection
                FullRepositoryId: AlexChesters/aws-sandbox-accounts
                BranchName: main
                OutputArtifactFormat: CODE_ZIP
        - Name: Build
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Build
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: Deploy-Apps-To-Test
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Account-Cleaner
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-aws-sandbox-accounts-account-cleaner
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/account-cleaner/stacks/sandbox-administrator-account/account-cleaner.yml
                TemplateConfiguration: BuildArtifact::apps/account-cleaner/stacks/sandbox-administrator-account/parameters/account-cleaner/test.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Account-Manager
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-aws-sandbox-accounts-account-manager
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/account-manager/stacks/sandbox-administrator-account/account-manager.yml
                TemplateConfiguration: BuildArtifact::apps/account-manager/stacks/sandbox-administrator-account/parameters/account-manager/test.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Lease-Creator
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-aws-sandbox-accounts-lease-creator
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/lease-creator/stacks/sandbox-administrator-account/lease-creator.yml
                TemplateConfiguration: BuildArtifact::apps/lease-creator/stacks/sandbox-administrator-account/parameters/lease-creator/test.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Lease-Janitor
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-aws-sandbox-accounts-lease-janitor
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/lease-janitor/stacks/sandbox-administrator-account/lease-janitor.yml
                TemplateConfiguration: BuildArtifact::apps/lease-janitor/stacks/sandbox-administrator-account/parameters/lease-janitor/test.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: DB-Client
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-aws-sandbox-accounts-db-client
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/db-client/stacks/sandbox-administrator-account/db-client.yml
                TemplateConfiguration: BuildArtifact::apps/db-client/stacks/sandbox-administrator-account/parameters/db-client/test.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Auth-Client
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-aws-sandbox-accounts-auth-client
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/auth-client/stacks/sandbox-administrator-account/auth-client.yml
                TemplateConfiguration: BuildArtifact::apps/auth-client/stacks/sandbox-administrator-account/parameters/auth-client/test.json
        - Name: Deploy-Apps-To-Live
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Account-Cleaner
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-aws-sandbox-accounts-account-cleaner
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/account-cleaner/stacks/sandbox-administrator-account/account-cleaner.yml
                TemplateConfiguration: BuildArtifact::apps/account-cleaner/stacks/sandbox-administrator-account/parameters/account-cleaner/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Account-Manager
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-aws-sandbox-accounts-account-manager
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/account-manager/stacks/sandbox-administrator-account/account-manager.yml
                TemplateConfiguration: BuildArtifact::apps/account-manager/stacks/sandbox-administrator-account/parameters/account-manager/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Lease-Creator
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-aws-sandbox-accounts-lease-creator
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/lease-creator/stacks/sandbox-administrator-account/lease-creator.yml
                TemplateConfiguration: BuildArtifact::apps/lease-creator/stacks/sandbox-administrator-account/parameters/lease-creator/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Lease-Janitor
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-aws-sandbox-accounts-lease-janitor
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/lease-janitor/stacks/sandbox-administrator-account/lease-janitor.yml
                TemplateConfiguration: BuildArtifact::apps/lease-janitor/stacks/sandbox-administrator-account/parameters/lease-janitor/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: DB-Client
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-aws-sandbox-accounts-db-client
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/db-client/stacks/sandbox-administrator-account/db-client.yml
                TemplateConfiguration: BuildArtifact::apps/db-client/stacks/sandbox-administrator-account/parameters/db-client/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
              Name: Auth-Client
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-aws-sandbox-accounts-auth-client
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-iam-role
                TemplatePath: BuildArtifact::apps/auth-client/stacks/sandbox-administrator-account/auth-client.yml
                TemplateConfiguration: BuildArtifact::apps/auth-client/stacks/sandbox-administrator-account/parameters/auth-client/live.json
