Description: dns records for the sandbox project
Parameters:
  Environment:
    Description: The infrastructure environment
    Type: String
    AllowedValues:
      - test
      - live
Mappings:
  EnvMap:
    test:
      DomainName: test.sandbox.alexchesters.com
    live:
      DomainName: sandbox.alexchesters.com
Resources:
  AuthCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub
        - "auth.${Domain}"
        - Domain: !FindInMap [EnvMap, !Ref Environment, DomainName]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub
            - "auth.${Domain}"
            - Domain: !FindInMap [EnvMap, !Ref Environment, DomainName]
          HostedZoneId: Z0160324S0RM0YHSCT4L
