Description: dns records for the sandbox project
Parameters:
  Environment:
    Description: The infrastructure environment
    Type: String
    AllowedValues:
      - test
      - live
Mappings:
  EnvMap:
    test:
      DomainName: test.sandbox.alexchesters.com
    live:
      DomainName: sandbox.alexchesters.com
Resources:
  # an A record is required for cognito custom domains
  # https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-add-custom-domain.html#cognito-user-pools-add-custom-domain-prereq
  CognitoARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue hosted-zone-id
      Name: !FindInMap [EnvMap, !Ref Environment, DomainName]
      Type: A
      TTL: '60'
      ResourceRecords:
        - "127.0.0.1"
